'use strict';

const DEFAULT_BATCH_SIZE = 200;
const MAX_BATCH_SIZE = 500;
const MIN_BATCH_SIZE = 100;
const DEFAULT_BASE_ENDPOINT = 'https://api.monkeylearn.com/v2/';

module.exports = {
    DEFAULT_BATCH_SIZE: DEFAULT_BATCH_SIZE,
    MAX_BATCH_SIZE: MAX_BATCH_SIZE,
    MIN_BATCH_SIZE: MIN_BATCH_SIZE,
    DEFAULT_BASE_ENDPOINT: DEFAULT_BASE_ENDPOINT,
};
